version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html

hooks:
  BeforeInstall:
    - location: scripts/before_install_ubuntu.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after_install_ubuntu.sh
      timeout: 300
      runas: root
    - location: scripts/database_start.sh # Create the MySQL database and user
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/application_start_ubuntu.sh
      timeout: 300
      runas: root
