version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.3
    commands:
      - echo "Installing dependencies"
      - sudo yum update -y
      - sudo yum install nginx -y
      - sudo yum install -y php php-fpm php-mysqlnd php-mbstring php-xml
      - echo Installing Composer...
      - curl -sS https://getcomposer.org/installer | php
      - sudo mv composer.phar /usr/local/bin/composer
      - composer install --no-dev --prefer-dist --optimize-autoloader
      - cp .env.example .env
      - php artisan key:generate

  pre_build:
    commands:
      - echo "Pre-build phase"

  build:
    commands:
      - echo "setting up the Laravel application..."
      - php artisan migrate
      - php artisan config:cache
      - php artisan route:cache
      - php artisan view:cache

  post_build:
    commands:
      - echo "Post-build phase"
      - sudo cp -r ./ /var/www/html/
      - sudo chown -R nginx:nginx /var/www/html/
      - sudo chmod -R 755 /var/www/html/

artifacts:
  files:
    - "public/**/*"
    - "resources/**/*"
    - "routes/**/*"
    - "storage/**/*"
    - "vendor/**/*"
    - "app/**/*"
    - "bootstrap/**/*"
    - "config/**/*"
    - "database/**/*"

cache:
  paths:
    - vendor/**/*
