version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.3
    commands:
      - echo "Installing dependencies"
      - sudo yum update -y
      - sudo yum install nginx -y
      - sudo amazon-linux-extras install epel -y
      - sudo yum install -y https://rpms.remirepo.net/enterprise/remi-release-7.rpm
      - sudo yum-config-manager --enable remi-php83
      - echo Installing PHP 8.3 and required extensions...
      - sudo yum install -y php php-fpm php-mysqlnd php-curl php-gd php-intl php-mbstring php-soap php-xml php-xmlrpc php-zip
      - sudo systemctl start php-fpm
      - sudo systemctl enable php-fpm
      - sudo systemctl start nginx1
      - sudo systemctl enable nginx1
      - composer install --no-dev --prefer-dist --optimize-autoloader
      - cp .env.example .env
      - php artisan key:generate

  pre_build:
    commands:
      - echo "Pre-build phase"

  build:
    commands:
      - echo "setting up the Laravel application..."
      - php artisan migrate
      - php artisan config:cache
      - php artisan route:cache
      - php artisan view:cache
      - php artisan db:seed

  post_build:
    commands:
      - echo "Post-build phase"
      - sudo cp -r /var/www/html
      - sudo chown -R www-data:www-data /var/www/html
      - sudo chmod -R 755 /var/www/html
      - sudo systemctl restart nginx1

artifacts:
  files:
    - "public/**/*"
    - "resources/**/*"
    - "routes/**/*"
    - "storage/**/*"
    - "vendor/**/*"
    - "app/**/*"
    - "bootstrap/**/*"
    - "config/**/*"
    - "database/**/*"

cache:
  paths:
    - vendor/**/*
